version: '{branch} build {build}'
image: Visual Studio 2019
platform:
  - x64
  - Win32
configuration: Release
clone_depth: 50
clone_folder: c:\projects\sentencepiece
#init:
# - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#on_finish:
# - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
build_script:
- cmd: call test.bat %platform%
artifacts:
 - path: build\sentencepiece*.7z
 - path: python\dist\*.whl
deploy:
  description: 'SentencePiece Windows release'
  provider: GitHub
  auth_token:
    secure: Aq4jHo/HY6WFFKs1h9cCWfi3U4ZsVTooUEhtgBfcJM6SUhnZdPVazIcKCtiR32kc
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
