/* This file was generated by upb_generator from the input file:
 *
 *     sentencepiece_model.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated.
 * NO CHECKED-IN PROTOBUF GENCODE */



#ifndef SENTENCEPIECE_MODEL_PROTO_UPB_H__UPBDEFS_H_
#define SENTENCEPIECE_MODEL_PROTO_UPB_H__UPBDEFS_H_

#include "upb/reflection/def.h"
#include "upb/reflection/internal/def_pool.h"

#include "upb/port/def.inc"

#ifdef __cplusplus
extern "C" {
#endif

extern _upb_DefPool_Init sentencepiece_model_proto_upbdefinit;

UPB_INLINE const upb_MessageDef *sentencepiece_TrainerSpec_getmsgdef(upb_DefPool *s) {
  _upb_DefPool_LoadDefInit(s, &sentencepiece_model_proto_upbdefinit);
  return upb_DefPool_FindMessageByName(s, "sentencepiece.TrainerSpec");
}

UPB_INLINE const upb_MessageDef *sentencepiece_NormalizerSpec_getmsgdef(upb_DefPool *s) {
  _upb_DefPool_LoadDefInit(s, &sentencepiece_model_proto_upbdefinit);
  return upb_DefPool_FindMessageByName(s, "sentencepiece.NormalizerSpec");
}

UPB_INLINE const upb_MessageDef *sentencepiece_SelfTestData_getmsgdef(upb_DefPool *s) {
  _upb_DefPool_LoadDefInit(s, &sentencepiece_model_proto_upbdefinit);
  return upb_DefPool_FindMessageByName(s, "sentencepiece.SelfTestData");
}

UPB_INLINE const upb_MessageDef *sentencepiece_SelfTestData_Sample_getmsgdef(upb_DefPool *s) {
  _upb_DefPool_LoadDefInit(s, &sentencepiece_model_proto_upbdefinit);
  return upb_DefPool_FindMessageByName(s, "sentencepiece.SelfTestData.Sample");
}

UPB_INLINE const upb_MessageDef *sentencepiece_ModelProto_getmsgdef(upb_DefPool *s) {
  _upb_DefPool_LoadDefInit(s, &sentencepiece_model_proto_upbdefinit);
  return upb_DefPool_FindMessageByName(s, "sentencepiece.ModelProto");
}

UPB_INLINE const upb_MessageDef *sentencepiece_ModelProto_SentencePiece_getmsgdef(upb_DefPool *s) {
  _upb_DefPool_LoadDefInit(s, &sentencepiece_model_proto_upbdefinit);
  return upb_DefPool_FindMessageByName(s, "sentencepiece.ModelProto.SentencePiece");
}


#ifdef __cplusplus
}  /* extern "C" */
#endif

#include "upb/port/undef.inc"

#endif  /* SENTENCEPIECE_MODEL_PROTO_UPB_H__UPBDEFS_H_ */
