/* This file was generated by upb_generator from the input file:
 *
 *     sentencepiece_model.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated.
 * NO CHECKED-IN PROTOBUF GENCODE */

#ifndef SENTENCEPIECE_MODEL_PROTO_UPB_H__UPB_MINITABLE_H_
#define SENTENCEPIECE_MODEL_PROTO_UPB_H__UPB_MINITABLE_H_

#include "upb.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const upb_MiniTable sentencepiece__TrainerSpec_msg_init;
extern const upb_MiniTable sentencepiece__NormalizerSpec_msg_init;
extern const upb_MiniTable sentencepiece__SelfTestData_msg_init;
extern const upb_MiniTable sentencepiece__SelfTestData__Sample_msg_init;
extern const upb_MiniTable sentencepiece__ModelProto_msg_init;
extern const upb_MiniTable sentencepiece__ModelProto__SentencePiece_msg_init;

extern const upb_MiniTableEnum sentencepiece__ModelProto__SentencePiece__Type_enum_init;
extern const upb_MiniTableEnum sentencepiece__TrainerSpec__ModelType_enum_init;
extern const upb_MiniTableFile sentencepiece_model_proto_upb_file_layout;

#ifdef __cplusplus
}  /* extern "C" */
#endif

#endif  /* SENTENCEPIECE_MODEL_PROTO_UPB_H__UPB_MINITABLE_H_ */
