/* This file was generated by upb_generator from the input file:
 *
 *     sentencepiece.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated.
 * NO CHECKED-IN PROTOBUF GENCODE */

#ifndef SENTENCEPIECE_PROTO_UPB_H__UPB_MINITABLE_H_
#define SENTENCEPIECE_PROTO_UPB_H__UPB_MINITABLE_H_

#include "upb.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const upb_MiniTable sentencepiece__SentencePieceText_msg_init;
extern const upb_MiniTable sentencepiece__SentencePieceText__SentencePiece_msg_init;
extern const upb_MiniTable sentencepiece__NBestSentencePieceText_msg_init;

extern const upb_MiniTableFile sentencepiece_proto_upb_file_layout;

#ifdef __cplusplus
}  /* extern "C" */
#endif

#endif  /* SENTENCEPIECE_PROTO_UPB_H__UPB_MINITABLE_H_ */
