/* This file was generated by upb_generator from the input file:
 *
 *     sentencepiece.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated.
 * NO CHECKED-IN PROTOBUF GENCODE */



#ifndef SENTENCEPIECE_PROTO_UPB_H__UPBDEFS_H_
#define SENTENCEPIECE_PROTO_UPB_H__UPBDEFS_H_

#include "upb/reflection/def.h"
#include "upb/reflection/internal/def_pool.h"

#include "upb/port/def.inc"

#ifdef __cplusplus
extern "C" {
#endif

extern _upb_DefPool_Init sentencepiece_proto_upbdefinit;

UPB_INLINE const upb_MessageDef *sentencepiece_SentencePieceText_getmsgdef(upb_DefPool *s) {
  _upb_DefPool_LoadDefInit(s, &sentencepiece_proto_upbdefinit);
  return upb_DefPool_FindMessageByName(s, "sentencepiece.SentencePieceText");
}

UPB_INLINE const upb_MessageDef *sentencepiece_SentencePieceText_SentencePiece_getmsgdef(upb_DefPool *s) {
  _upb_DefPool_LoadDefInit(s, &sentencepiece_proto_upbdefinit);
  return upb_DefPool_FindMessageByName(s, "sentencepiece.SentencePieceText.SentencePiece");
}

UPB_INLINE const upb_MessageDef *sentencepiece_NBestSentencePieceText_getmsgdef(upb_DefPool *s) {
  _upb_DefPool_LoadDefInit(s, &sentencepiece_proto_upbdefinit);
  return upb_DefPool_FindMessageByName(s, "sentencepiece.NBestSentencePieceText");
}


#ifdef __cplusplus
}  /* extern "C" */
#endif

#include "upb/port/undef.inc"

#endif  /* SENTENCEPIECE_PROTO_UPB_H__UPBDEFS_H_ */
