/* This file was generated by upb_generator from the input file:
 *
 *     sentencepiece.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated.
 * NO CHECKED-IN PROTOBUF GENCODE */

#include <stddef.h>
#include "upb.h"
#include "sentencepiece.upb_minitable.h"

extern const UPB_PRIVATE(upb_GeneratedExtensionListEntry)* UPB_PRIVATE(upb_generated_extension_list);
typedef struct {
  upb_MiniTableField fields[3];
  upb_MiniTableSubInternal subs[1];
} sentencepiece__SentencePieceText_msg_init_Fields;

static const sentencepiece__SentencePieceText_msg_init_Fields sentencepiece_SentencePieceText__fields = {{
  {1, UPB_SIZE(20, 16), 64, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {2, UPB_SIZE(12, 32), 0, UPB_SIZE(6, 7), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {3, UPB_SIZE(16, 12), 65, kUpb_NoSub, 2, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
 },
  {
  {.UPB_PRIVATE(submsg) = &sentencepiece__SentencePieceText__SentencePiece_msg_init},
}};

const upb_MiniTable sentencepiece__SentencePieceText_msg_init = {
  &sentencepiece_SentencePieceText__fields.fields[0],
  UPB_SIZE(32, 40), 3, kUpb_ExtMode_Extendable, 3, UPB_FASTTABLE_MASK(24), 0,
#ifdef UPB_TRACING_ENABLED
  "sentencepiece.SentencePieceText",
#endif
  UPB_FASTTABLE_INIT({
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x001000000000000a, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x000c00000100001d, &upb_DecodeFast_Fixed32_Scalar_Tag1Byte},
  })
};

typedef struct {
  upb_MiniTableField fields[5];
} sentencepiece__SentencePieceText__SentencePiece_msg_init_Fields;

static const sentencepiece__SentencePieceText__SentencePiece_msg_init_Fields sentencepiece_SentencePieceText_SentencePiece__fields = {{
  {1, 24, 64, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {2, 12, 65, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {3, UPB_SIZE(32, 40), 66, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {4, 16, 67, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {5, 20, 68, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
}};

const upb_MiniTable sentencepiece__SentencePieceText__SentencePiece_msg_init = {
  &sentencepiece_SentencePieceText_SentencePiece__fields.fields[0],
  UPB_SIZE(40, 56), 5, kUpb_ExtMode_Extendable, 5, UPB_FASTTABLE_MASK(56), 0,
#ifdef UPB_TRACING_ENABLED
  "sentencepiece.SentencePieceText.SentencePiece",
#endif
  UPB_FASTTABLE_INIT({
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x001800000000000a, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x000c000001000010, &upb_DecodeFast_Varint32_Scalar_Tag1Byte},
    {0x002800000200001a, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x0010000003000020, &upb_DecodeFast_Varint32_Scalar_Tag1Byte},
    {0x0014000004000028, &upb_DecodeFast_Varint32_Scalar_Tag1Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
  })
};

typedef struct {
  upb_MiniTableField fields[1];
  upb_MiniTableSubInternal subs[1];
} sentencepiece__NBestSentencePieceText_msg_init_Fields;

static const sentencepiece__NBestSentencePieceText_msg_init_Fields sentencepiece_NBestSentencePieceText__fields = {{
  {1, 8, 0, UPB_SIZE(3, 4), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
 },
  {
  {.UPB_PRIVATE(submsg) = &sentencepiece__SentencePieceText_msg_init},
}};

const upb_MiniTable sentencepiece__NBestSentencePieceText_msg_init = {
  &sentencepiece_NBestSentencePieceText__fields.fields[0],
  16, 1, kUpb_ExtMode_NonExtendable, 1, UPB_FASTTABLE_MASK(255), 0,
#ifdef UPB_TRACING_ENABLED
  "sentencepiece.NBestSentencePieceText",
#endif
};

static const upb_MiniTable *messages_layout[3] = {
  &sentencepiece__SentencePieceText_msg_init,
  &sentencepiece__SentencePieceText__SentencePiece_msg_init,
  &sentencepiece__NBestSentencePieceText_msg_init,
};

const upb_MiniTableFile sentencepiece_proto_upb_file_layout = {
  messages_layout,
  NULL,
  NULL,
  3,
  0,
  0,
};

