/* This file was generated by upb_generator from the input file:
 *
 *     sentencepiece_model.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated.
 * NO CHECKED-IN PROTOBUF GENCODE */

#include <stddef.h>
#include "upb.h"
#include "sentencepiece_model.upb_minitable.h"

extern const UPB_PRIVATE(upb_GeneratedExtensionListEntry)* UPB_PRIVATE(upb_generated_extension_list);
typedef struct {
  upb_MiniTableField fields[46];
  upb_MiniTableSubInternal subs[1];
} sentencepiece__TrainerSpec_msg_init_Fields;

static const sentencepiece__TrainerSpec_msg_init_Fields sentencepiece_TrainerSpec__fields = {{
  {1, UPB_SIZE(28, 256), 0, kUpb_NoSub, 12, (int)kUpb_FieldMode_Array | (int)kUpb_LabelFlags_IsAlternate | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {2, UPB_SIZE(112, 96), 64, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {3, UPB_SIZE(32, 28), 65, 132, 14, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {4, UPB_SIZE(36, 32), 66, kUpb_NoSub, 5, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {5, UPB_SIZE(40, 264), 0, kUpb_NoSub, 12, (int)kUpb_FieldMode_Array | (int)kUpb_LabelFlags_IsAlternate | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {6, UPB_SIZE(44, 36), 67, kUpb_NoSub, 5, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {7, UPB_SIZE(120, 112), 68, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {10, UPB_SIZE(48, 40), 69, kUpb_NoSub, 2, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {11, UPB_SIZE(192, 272), 70, kUpb_NoSub, 4, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_8Byte << kUpb_FieldRep_Shift)},
  {12, UPB_SIZE(52, 44), 71, kUpb_NoSub, 5, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {13, UPB_SIZE(56, 48), 72, kUpb_NoSub, 5, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {14, UPB_SIZE(60, 52), 73, kUpb_NoSub, 5, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {15, UPB_SIZE(64, 56), 74, kUpb_NoSub, 2, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {16, UPB_SIZE(68, 60), 75, kUpb_NoSub, 5, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {17, UPB_SIZE(72, 64), 76, kUpb_NoSub, 5, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {18, UPB_SIZE(76, 68), 77, kUpb_NoSub, 5, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {19, 14, 78, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
  {20, UPB_SIZE(80, 72), 79, kUpb_NoSub, 5, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {21, 15, 80, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
  {22, 16, 81, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
  {23, 17, 82, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
  {24, 18, 83, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
  {25, 19, 84, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
  {26, 20, 85, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
  {30, UPB_SIZE(84, 280), 0, kUpb_NoSub, 12, (int)kUpb_FieldMode_Array | (int)kUpb_LabelFlags_IsAlternate | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {31, UPB_SIZE(88, 288), 0, kUpb_NoSub, 12, (int)kUpb_FieldMode_Array | (int)kUpb_LabelFlags_IsAlternate | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {32, 21, 86, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
  {33, 22, 87, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
  {34, 23, 88, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
  {35, 24, 89, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
  {36, 128, 90, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {40, UPB_SIZE(92, 76), 91, kUpb_NoSub, 5, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {41, UPB_SIZE(96, 80), 92, kUpb_NoSub, 5, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {42, UPB_SIZE(100, 84), 93, kUpb_NoSub, 5, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {43, UPB_SIZE(104, 88), 94, kUpb_NoSub, 5, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {44, UPB_SIZE(136, 144), 95, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {45, UPB_SIZE(144, 160), 96, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {46, UPB_SIZE(152, 176), 97, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {47, UPB_SIZE(160, 192), 98, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {48, UPB_SIZE(168, 208), 99, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {49, 25, 100, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
  {50, 26, 101, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
  {51, UPB_SIZE(108, 92), 102, kUpb_NoSub, 2, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {52, UPB_SIZE(200, 296), 103, kUpb_NoSub, 4, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_8Byte << kUpb_FieldRep_Shift)},
  {53, UPB_SIZE(176, 224), 104, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {54, UPB_SIZE(184, 240), 105, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
 },
  {
  {.UPB_PRIVATE(subenum) = &sentencepiece__TrainerSpec__ModelType_enum_init},
}};

const upb_MiniTable sentencepiece__TrainerSpec_msg_init = {
  &sentencepiece_TrainerSpec__fields.fields[0],
  UPB_SIZE(208, 304), 46, kUpb_ExtMode_Extendable, 7, UPB_FASTTABLE_MASK(248), 0,
#ifdef UPB_TRACING_ENABLED
  "sentencepiece.TrainerSpec",
#endif
  UPB_FASTTABLE_INIT({
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x010000003f00000a, &upb_DecodeFast_Bytes_Repeated_Tag1Byte},
    {0x0060000000000012, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0020000002000020, &upb_DecodeFast_Varint32_Scalar_Tag1Byte},
    {0x010800003f00002a, &upb_DecodeFast_Bytes_Repeated_Tag1Byte},
    {0x0024000003000030, &upb_DecodeFast_Varint32_Scalar_Tag1Byte},
    {0x007000000400003a, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x0028000005000055, &upb_DecodeFast_Fixed32_Scalar_Tag1Byte},
    {0x0110000006000058, &upb_DecodeFast_Varint64_Scalar_Tag1Byte},
    {0x002c000007000060, &upb_DecodeFast_Varint32_Scalar_Tag1Byte},
    {0x0030000008000068, &upb_DecodeFast_Varint32_Scalar_Tag1Byte},
    {0x0034000009000070, &upb_DecodeFast_Varint32_Scalar_Tag1Byte},
    {0x003800000a00007d, &upb_DecodeFast_Fixed32_Scalar_Tag1Byte},
    {0x003c00000b000180, &upb_DecodeFast_Varint32_Scalar_Tag2Byte},
    {0x004000000c000188, &upb_DecodeFast_Varint32_Scalar_Tag2Byte},
    {0x004400000d000190, &upb_DecodeFast_Varint32_Scalar_Tag2Byte},
    {0x000e00000e000198, &upb_DecodeFast_Bool_Scalar_Tag2Byte},
    {0x004800000f0001a0, &upb_DecodeFast_Varint32_Scalar_Tag2Byte},
    {0x000f0000100001a8, &upb_DecodeFast_Bool_Scalar_Tag2Byte},
    {0x00100000110001b0, &upb_DecodeFast_Bool_Scalar_Tag2Byte},
    {0x00110000120001b8, &upb_DecodeFast_Bool_Scalar_Tag2Byte},
    {0x00120000130001c0, &upb_DecodeFast_Bool_Scalar_Tag2Byte},
    {0x00130000140001c8, &upb_DecodeFast_Bool_Scalar_Tag2Byte},
    {0x00140000150001d0, &upb_DecodeFast_Bool_Scalar_Tag2Byte},
    {0x005800001e0002d8, &upb_DecodeFast_Varint32_Scalar_Tag2Byte},
    {0x009000001f0002e2, &upb_DecodeFast_Bytes_Scalar_Tag2Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x011800003f0001f2, &upb_DecodeFast_Bytes_Repeated_Tag2Byte},
    {0x012000003f0001fa, &upb_DecodeFast_Bytes_Repeated_Tag2Byte},
  })
};

typedef struct {
  upb_MiniTableField fields[6];
} sentencepiece__NormalizerSpec_msg_init_Fields;

static const sentencepiece__NormalizerSpec_msg_init_Fields sentencepiece_NormalizerSpec__fields = {{
  {1, UPB_SIZE(12, 16), 64, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {2, UPB_SIZE(20, 32), 65, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {3, 9, 66, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
  {4, 10, 67, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
  {5, 11, 68, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
  {6, UPB_SIZE(28, 48), 69, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
}};

const upb_MiniTable sentencepiece__NormalizerSpec_msg_init = {
  &sentencepiece_NormalizerSpec__fields.fields[0],
  UPB_SIZE(40, 64), 6, kUpb_ExtMode_Extendable, 6, UPB_FASTTABLE_MASK(56), 0,
#ifdef UPB_TRACING_ENABLED
  "sentencepiece.NormalizerSpec",
#endif
  UPB_FASTTABLE_INIT({
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x001000000000000a, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x0020000001000012, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x0009000002000018, &upb_DecodeFast_Bool_Scalar_Tag1Byte},
    {0x000a000003000020, &upb_DecodeFast_Bool_Scalar_Tag1Byte},
    {0x000b000004000028, &upb_DecodeFast_Bool_Scalar_Tag1Byte},
    {0x0030000005000032, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
  })
};

typedef struct {
  upb_MiniTableField fields[1];
  upb_MiniTableSubInternal subs[1];
} sentencepiece__SelfTestData_msg_init_Fields;

static const sentencepiece__SelfTestData_msg_init_Fields sentencepiece_SelfTestData__fields = {{
  {1, 8, 0, UPB_SIZE(3, 4), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
 },
  {
  {.UPB_PRIVATE(submsg) = &sentencepiece__SelfTestData__Sample_msg_init},
}};

const upb_MiniTable sentencepiece__SelfTestData_msg_init = {
  &sentencepiece_SelfTestData__fields.fields[0],
  16, 1, kUpb_ExtMode_Extendable, 1, UPB_FASTTABLE_MASK(255), 0,
#ifdef UPB_TRACING_ENABLED
  "sentencepiece.SelfTestData",
#endif
};

typedef struct {
  upb_MiniTableField fields[2];
} sentencepiece__SelfTestData__Sample_msg_init_Fields;

static const sentencepiece__SelfTestData__Sample_msg_init_Fields sentencepiece_SelfTestData_Sample__fields = {{
  {1, UPB_SIZE(12, 16), 64, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {2, UPB_SIZE(20, 32), 65, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
}};

const upb_MiniTable sentencepiece__SelfTestData__Sample_msg_init = {
  &sentencepiece_SelfTestData_Sample__fields.fields[0],
  UPB_SIZE(32, 48), 2, kUpb_ExtMode_NonExtendable, 2, UPB_FASTTABLE_MASK(24), 0,
#ifdef UPB_TRACING_ENABLED
  "sentencepiece.SelfTestData.Sample",
#endif
  UPB_FASTTABLE_INIT({
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x001000000000000a, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x0020000001000012, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
  })
};

typedef struct {
  upb_MiniTableField fields[5];
  upb_MiniTableSubInternal subs[5];
} sentencepiece__ModelProto_msg_init_Fields;

static const sentencepiece__ModelProto_msg_init_Fields sentencepiece_ModelProto__fields = {{
  {1, UPB_SIZE(12, 16), 0, UPB_SIZE(15, 16), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {2, UPB_SIZE(16, 24), 64, UPB_SIZE(13, 15), 11, (int)kUpb_FieldMode_Scalar | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {3, UPB_SIZE(20, 32), 65, UPB_SIZE(11, 14), 11, (int)kUpb_FieldMode_Scalar | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {4, UPB_SIZE(24, 40), 66, UPB_SIZE(9, 13), 11, (int)kUpb_FieldMode_Scalar | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {5, UPB_SIZE(28, 48), 67, UPB_SIZE(7, 12), 11, (int)kUpb_FieldMode_Scalar | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
 },
  {
  {.UPB_PRIVATE(submsg) = &sentencepiece__ModelProto__SentencePiece_msg_init},
  {.UPB_PRIVATE(submsg) = &sentencepiece__TrainerSpec_msg_init},
  {.UPB_PRIVATE(submsg) = &sentencepiece__NormalizerSpec_msg_init},
  {.UPB_PRIVATE(submsg) = &sentencepiece__SelfTestData_msg_init},
  {.UPB_PRIVATE(submsg) = &sentencepiece__NormalizerSpec_msg_init},
}};

const upb_MiniTable sentencepiece__ModelProto_msg_init = {
  &sentencepiece_ModelProto__fields.fields[0],
  UPB_SIZE(32, 56), 5, kUpb_ExtMode_Extendable, 5, UPB_FASTTABLE_MASK(255), 0,
#ifdef UPB_TRACING_ENABLED
  "sentencepiece.ModelProto",
#endif
};

typedef struct {
  upb_MiniTableField fields[3];
  upb_MiniTableSubInternal subs[1];
} sentencepiece__ModelProto__SentencePiece_msg_init_Fields;

static const sentencepiece__ModelProto__SentencePiece_msg_init_Fields sentencepiece_ModelProto_SentencePiece__fields = {{
  {1, UPB_SIZE(20, 24), 64, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)},
  {2, 12, 65, kUpb_NoSub, 2, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
  {3, 16, 66, UPB_SIZE(3, 4), 14, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)},
 },
  {
  {.UPB_PRIVATE(subenum) = &sentencepiece__ModelProto__SentencePiece__Type_enum_init},
}};

const upb_MiniTable sentencepiece__ModelProto__SentencePiece_msg_init = {
  &sentencepiece_ModelProto_SentencePiece__fields.fields[0],
  UPB_SIZE(32, 40), 3, kUpb_ExtMode_Extendable, 3, UPB_FASTTABLE_MASK(24), 0,
#ifdef UPB_TRACING_ENABLED
  "sentencepiece.ModelProto.SentencePiece",
#endif
  UPB_FASTTABLE_INIT({
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
    {0x001800000000000a, &upb_DecodeFast_Bytes_Scalar_Tag1Byte},
    {0x000c000001000015, &upb_DecodeFast_Fixed32_Scalar_Tag1Byte},
    {0x0000000000000000, &_upb_FastDecoder_DecodeGeneric},
  })
};

const upb_MiniTableEnum sentencepiece__ModelProto__SentencePiece__Type_enum_init = {
    64,
    0,
    {
        0x7e,
        0x0,
    },
};

const upb_MiniTableEnum sentencepiece__TrainerSpec__ModelType_enum_init = {
    64,
    0,
    {
        0x1e,
        0x0,
    },
};

static const upb_MiniTable *messages_layout[6] = {
  &sentencepiece__TrainerSpec_msg_init,
  &sentencepiece__NormalizerSpec_msg_init,
  &sentencepiece__SelfTestData_msg_init,
  &sentencepiece__SelfTestData__Sample_msg_init,
  &sentencepiece__ModelProto_msg_init,
  &sentencepiece__ModelProto__SentencePiece_msg_init,
};

static const upb_MiniTableEnum *enums_layout[2] = {
  &sentencepiece__ModelProto__SentencePiece__Type_enum_init,
  &sentencepiece__TrainerSpec__ModelType_enum_init,
};

const upb_MiniTableFile sentencepiece_model_proto_upb_file_layout = {
  messages_layout,
  enums_layout,
  NULL,
  6,
  2,
  0,
};


