/* This file was generated by upb_generator from the input file:
 *
 *     sentencepiece.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated.
 * NO CHECKED-IN PROTOBUF GENCODE */

#ifndef SENTENCEPIECE_PROTO_UPB_H__UPB_H_
#define SENTENCEPIECE_PROTO_UPB_H__UPB_H_

#include "upb.h"
#include "sentencepiece.upb_minitable.h"

#ifdef __cplusplus
extern "C" {
#endif
typedef struct sentencepiece_SentencePieceText {
  upb_Message UPB_PRIVATE(base);
} sentencepiece_SentencePieceText;

typedef struct sentencepiece_SentencePieceText_SentencePiece {
  upb_Message UPB_PRIVATE(base);
} sentencepiece_SentencePieceText_SentencePiece;

typedef struct sentencepiece_NBestSentencePieceText {
  upb_Message UPB_PRIVATE(base);
} sentencepiece_NBestSentencePieceText;




/* sentencepiece.SentencePieceText */
UPB_INLINE sentencepiece_SentencePieceText* sentencepiece_SentencePieceText_new(upb_Arena* arena) {
  return (sentencepiece_SentencePieceText*)_upb_Message_New(&sentencepiece__SentencePieceText_msg_init, arena);
}
UPB_INLINE sentencepiece_SentencePieceText* sentencepiece_SentencePieceText_parse(const char* buf, size_t size,
                                        upb_Arena* arena) {
  sentencepiece_SentencePieceText* ret = sentencepiece_SentencePieceText_new(arena);
  if (!ret) return NULL;
  if (upb_Decode(buf, size, UPB_UPCAST(ret), &sentencepiece__SentencePieceText_msg_init, NULL, 0,
                 arena) != kUpb_DecodeStatus_Ok) {
    return NULL;
  }
  return ret;
}
UPB_INLINE sentencepiece_SentencePieceText* sentencepiece_SentencePieceText_parse_ex(
    const char* buf, size_t size, const upb_ExtensionRegistry* extreg,
    int options, upb_Arena* arena) {
  sentencepiece_SentencePieceText* ret = sentencepiece_SentencePieceText_new(arena);
  if (!ret) return NULL;
  if (upb_Decode(buf, size, UPB_UPCAST(ret), &sentencepiece__SentencePieceText_msg_init, extreg,
                 options, arena) != kUpb_DecodeStatus_Ok) {
    return NULL;
  }
  return ret;
}
UPB_INLINE char* sentencepiece_SentencePieceText_serialize(const sentencepiece_SentencePieceText* msg,
                                      upb_Arena* arena, size_t* len) {
  char* ptr;
  (void)upb_Encode(UPB_UPCAST(msg), &sentencepiece__SentencePieceText_msg_init, 0, arena, &ptr, len);
  return ptr;
}
UPB_INLINE char* sentencepiece_SentencePieceText_serialize_ex(const sentencepiece_SentencePieceText* msg,
                                         int options, upb_Arena* arena,
                                         size_t* len) {
  char* ptr;
  (void)upb_Encode(UPB_UPCAST(msg), &sentencepiece__SentencePieceText_msg_init, options, arena, &ptr, len);
  return ptr;
}
UPB_INLINE void sentencepiece_SentencePieceText_clear_text(sentencepiece_SentencePieceText* msg) {
  const upb_MiniTableField field = {1, UPB_SIZE(20, 16), 64, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  upb_Message_ClearBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE upb_StringView sentencepiece_SentencePieceText_text(const sentencepiece_SentencePieceText* msg) {
  upb_StringView default_val = upb_StringView_FromString("");
  upb_StringView ret;
  const upb_MiniTableField field = {1, UPB_SIZE(20, 16), 64, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  _upb_Message_GetNonExtensionField(UPB_UPCAST(msg), &field,
                                    &default_val, &ret);
  return ret;
}
UPB_INLINE bool sentencepiece_SentencePieceText_has_text(const sentencepiece_SentencePieceText* msg) {
  const upb_MiniTableField field = {1, UPB_SIZE(20, 16), 64, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  return upb_Message_HasBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE void sentencepiece_SentencePieceText_clear_pieces(sentencepiece_SentencePieceText* msg) {
  const upb_MiniTableField field = {2, UPB_SIZE(12, 32), 0, UPB_SIZE(6, 7), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)};
  upb_Message_ClearBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE const sentencepiece_SentencePieceText_SentencePiece* const* sentencepiece_SentencePieceText_pieces(const sentencepiece_SentencePieceText* msg,
                                                  size_t* size) {
  const upb_MiniTableField field = {2, UPB_SIZE(12, 32), 0, UPB_SIZE(6, 7), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)};
  UPB_PRIVATE(_upb_MiniTable_StrongReference)(&sentencepiece__SentencePieceText__SentencePiece_msg_init);
  const upb_Array* arr = upb_Message_GetArray(UPB_UPCAST(msg), &field);
  if (arr) {
    if (size) *size = arr->UPB_PRIVATE(size);
    return (const sentencepiece_SentencePieceText_SentencePiece* const*)upb_Array_DataPtr(arr);
  } else {
    if (size) *size = 0;
    return NULL;
  }
}

//
UPB_INLINE const upb_Array* _sentencepiece_SentencePieceText_pieces_upb_array(
    const sentencepiece_SentencePieceText* msg, size_t* size) {
  const upb_MiniTableField field = {2, UPB_SIZE(12, 32), 0, UPB_SIZE(6, 7), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)};
  UPB_PRIVATE(_upb_MiniTable_StrongReference)(&sentencepiece__SentencePieceText__SentencePiece_msg_init);
  const upb_Array* arr = upb_Message_GetArray(UPB_UPCAST(msg), &field);
  if (size) {
    *size = arr ? arr->UPB_PRIVATE(size) : 0;
  }
  return arr;
}

UPB_INLINE upb_Array* _sentencepiece_SentencePieceText_pieces_mutable_upb_array(
    sentencepiece_SentencePieceText* msg, size_t* size, upb_Arena* arena) {
  const upb_MiniTableField field = {2, UPB_SIZE(12, 32), 0, UPB_SIZE(6, 7), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)};
  UPB_PRIVATE(_upb_MiniTable_StrongReference)(&sentencepiece__SentencePieceText__SentencePiece_msg_init);
  upb_Array* arr = upb_Message_GetOrCreateMutableArray(UPB_UPCAST(msg),
                                                       &field, arena);
  if (size) {
    *size = arr ? arr->UPB_PRIVATE(size) : 0;
  }
  return arr;
}
UPB_INLINE void sentencepiece_SentencePieceText_clear_score(sentencepiece_SentencePieceText* msg) {
  const upb_MiniTableField field = {3, UPB_SIZE(16, 12), 65, kUpb_NoSub, 2, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  upb_Message_ClearBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE float sentencepiece_SentencePieceText_score(const sentencepiece_SentencePieceText* msg) {
  float default_val = 0;
  float ret;
  const upb_MiniTableField field = {3, UPB_SIZE(16, 12), 65, kUpb_NoSub, 2, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  _upb_Message_GetNonExtensionField(UPB_UPCAST(msg), &field,
                                    &default_val, &ret);
  return ret;
}
UPB_INLINE bool sentencepiece_SentencePieceText_has_score(const sentencepiece_SentencePieceText* msg) {
  const upb_MiniTableField field = {3, UPB_SIZE(16, 12), 65, kUpb_NoSub, 2, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  return upb_Message_HasBaseField(UPB_UPCAST(msg), &field);
}

UPB_INLINE void sentencepiece_SentencePieceText_set_text(sentencepiece_SentencePieceText* msg, upb_StringView value) {
  const upb_MiniTableField field = {1, UPB_SIZE(20, 16), 64, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  upb_Message_SetBaseField((upb_Message*)msg, &field, &value);
}
UPB_INLINE sentencepiece_SentencePieceText_SentencePiece** sentencepiece_SentencePieceText_mutable_pieces(sentencepiece_SentencePieceText* msg,
                                              size_t* size) {
  upb_MiniTableField field = {2, UPB_SIZE(12, 32), 0, UPB_SIZE(6, 7), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)};
  UPB_PRIVATE(_upb_MiniTable_StrongReference)(&sentencepiece__SentencePieceText__SentencePiece_msg_init);
  upb_Array* arr = upb_Message_GetMutableArray(UPB_UPCAST(msg), &field);
  if (arr) {
    if (size) *size = arr->UPB_PRIVATE(size);
    return (sentencepiece_SentencePieceText_SentencePiece**)upb_Array_MutableDataPtr(arr);
  } else {
    if (size) *size = 0;
    return NULL;
  }
}

UPB_INLINE sentencepiece_SentencePieceText_SentencePiece** sentencepiece_SentencePieceText_resize_pieces(sentencepiece_SentencePieceText* msg,
                                             size_t size,
                                             upb_Arena* arena) {
  upb_MiniTableField field = {2, UPB_SIZE(12, 32), 0, UPB_SIZE(6, 7), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)};
  UPB_PRIVATE(_upb_MiniTable_StrongReference)(&sentencepiece__SentencePieceText__SentencePiece_msg_init);
  return (sentencepiece_SentencePieceText_SentencePiece**)upb_Message_ResizeArrayUninitialized(
      UPB_UPCAST(msg), &field, size, arena);
}
UPB_INLINE struct sentencepiece_SentencePieceText_SentencePiece* sentencepiece_SentencePieceText_add_pieces(
    sentencepiece_SentencePieceText* msg, upb_Arena* arena) {
  upb_MiniTableField field = {2, UPB_SIZE(12, 32), 0, UPB_SIZE(6, 7), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)};
  UPB_PRIVATE(_upb_MiniTable_StrongReference)(&sentencepiece__SentencePieceText__SentencePiece_msg_init);
  upb_Array* arr = upb_Message_GetOrCreateMutableArray(
      UPB_UPCAST(msg), &field, arena);
  if (!arr || !UPB_PRIVATE(_upb_Array_ResizeUninitialized)(
                  arr, arr->UPB_PRIVATE(size) + 1, arena)) {
    return NULL;
  }
  struct sentencepiece_SentencePieceText_SentencePiece* sub =
      (struct sentencepiece_SentencePieceText_SentencePiece*)_upb_Message_New(&sentencepiece__SentencePieceText__SentencePiece_msg_init, arena);
  if (!arr || !sub) return NULL;
  UPB_PRIVATE(_upb_Array_Set)
  (arr, arr->UPB_PRIVATE(size) - 1, &sub, sizeof(sub));
  return sub;
}
UPB_INLINE void sentencepiece_SentencePieceText_set_score(sentencepiece_SentencePieceText* msg, float value) {
  const upb_MiniTableField field = {3, UPB_SIZE(16, 12), 65, kUpb_NoSub, 2, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  upb_Message_SetBaseField((upb_Message*)msg, &field, &value);
}

/* sentencepiece.SentencePieceText.SentencePiece */
UPB_INLINE sentencepiece_SentencePieceText_SentencePiece* sentencepiece_SentencePieceText_SentencePiece_new(upb_Arena* arena) {
  return (sentencepiece_SentencePieceText_SentencePiece*)_upb_Message_New(&sentencepiece__SentencePieceText__SentencePiece_msg_init, arena);
}
UPB_INLINE sentencepiece_SentencePieceText_SentencePiece* sentencepiece_SentencePieceText_SentencePiece_parse(const char* buf, size_t size,
                                        upb_Arena* arena) {
  sentencepiece_SentencePieceText_SentencePiece* ret = sentencepiece_SentencePieceText_SentencePiece_new(arena);
  if (!ret) return NULL;
  if (upb_Decode(buf, size, UPB_UPCAST(ret), &sentencepiece__SentencePieceText__SentencePiece_msg_init, NULL, 0,
                 arena) != kUpb_DecodeStatus_Ok) {
    return NULL;
  }
  return ret;
}
UPB_INLINE sentencepiece_SentencePieceText_SentencePiece* sentencepiece_SentencePieceText_SentencePiece_parse_ex(
    const char* buf, size_t size, const upb_ExtensionRegistry* extreg,
    int options, upb_Arena* arena) {
  sentencepiece_SentencePieceText_SentencePiece* ret = sentencepiece_SentencePieceText_SentencePiece_new(arena);
  if (!ret) return NULL;
  if (upb_Decode(buf, size, UPB_UPCAST(ret), &sentencepiece__SentencePieceText__SentencePiece_msg_init, extreg,
                 options, arena) != kUpb_DecodeStatus_Ok) {
    return NULL;
  }
  return ret;
}
UPB_INLINE char* sentencepiece_SentencePieceText_SentencePiece_serialize(const sentencepiece_SentencePieceText_SentencePiece* msg,
                                      upb_Arena* arena, size_t* len) {
  char* ptr;
  (void)upb_Encode(UPB_UPCAST(msg), &sentencepiece__SentencePieceText__SentencePiece_msg_init, 0, arena, &ptr, len);
  return ptr;
}
UPB_INLINE char* sentencepiece_SentencePieceText_SentencePiece_serialize_ex(const sentencepiece_SentencePieceText_SentencePiece* msg,
                                         int options, upb_Arena* arena,
                                         size_t* len) {
  char* ptr;
  (void)upb_Encode(UPB_UPCAST(msg), &sentencepiece__SentencePieceText__SentencePiece_msg_init, options, arena, &ptr, len);
  return ptr;
}
UPB_INLINE void sentencepiece_SentencePieceText_SentencePiece_clear_piece(sentencepiece_SentencePieceText_SentencePiece* msg) {
  const upb_MiniTableField field = {1, 24, 64, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  upb_Message_ClearBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE upb_StringView sentencepiece_SentencePieceText_SentencePiece_piece(const sentencepiece_SentencePieceText_SentencePiece* msg) {
  upb_StringView default_val = upb_StringView_FromString("");
  upb_StringView ret;
  const upb_MiniTableField field = {1, 24, 64, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  _upb_Message_GetNonExtensionField(UPB_UPCAST(msg), &field,
                                    &default_val, &ret);
  return ret;
}
UPB_INLINE bool sentencepiece_SentencePieceText_SentencePiece_has_piece(const sentencepiece_SentencePieceText_SentencePiece* msg) {
  const upb_MiniTableField field = {1, 24, 64, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  return upb_Message_HasBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE void sentencepiece_SentencePieceText_SentencePiece_clear_id(sentencepiece_SentencePieceText_SentencePiece* msg) {
  const upb_MiniTableField field = {2, 12, 65, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  upb_Message_ClearBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE uint32_t sentencepiece_SentencePieceText_SentencePiece_id(const sentencepiece_SentencePieceText_SentencePiece* msg) {
  uint32_t default_val = (uint32_t)0u;
  uint32_t ret;
  const upb_MiniTableField field = {2, 12, 65, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  _upb_Message_GetNonExtensionField(UPB_UPCAST(msg), &field,
                                    &default_val, &ret);
  return ret;
}
UPB_INLINE bool sentencepiece_SentencePieceText_SentencePiece_has_id(const sentencepiece_SentencePieceText_SentencePiece* msg) {
  const upb_MiniTableField field = {2, 12, 65, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  return upb_Message_HasBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE void sentencepiece_SentencePieceText_SentencePiece_clear_surface(sentencepiece_SentencePieceText_SentencePiece* msg) {
  const upb_MiniTableField field = {3, UPB_SIZE(32, 40), 66, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  upb_Message_ClearBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE upb_StringView sentencepiece_SentencePieceText_SentencePiece_surface(const sentencepiece_SentencePieceText_SentencePiece* msg) {
  upb_StringView default_val = upb_StringView_FromString("");
  upb_StringView ret;
  const upb_MiniTableField field = {3, UPB_SIZE(32, 40), 66, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  _upb_Message_GetNonExtensionField(UPB_UPCAST(msg), &field,
                                    &default_val, &ret);
  return ret;
}
UPB_INLINE bool sentencepiece_SentencePieceText_SentencePiece_has_surface(const sentencepiece_SentencePieceText_SentencePiece* msg) {
  const upb_MiniTableField field = {3, UPB_SIZE(32, 40), 66, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  return upb_Message_HasBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE void sentencepiece_SentencePieceText_SentencePiece_clear_begin(sentencepiece_SentencePieceText_SentencePiece* msg) {
  const upb_MiniTableField field = {4, 16, 67, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  upb_Message_ClearBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE uint32_t sentencepiece_SentencePieceText_SentencePiece_begin(const sentencepiece_SentencePieceText_SentencePiece* msg) {
  uint32_t default_val = (uint32_t)0u;
  uint32_t ret;
  const upb_MiniTableField field = {4, 16, 67, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  _upb_Message_GetNonExtensionField(UPB_UPCAST(msg), &field,
                                    &default_val, &ret);
  return ret;
}
UPB_INLINE bool sentencepiece_SentencePieceText_SentencePiece_has_begin(const sentencepiece_SentencePieceText_SentencePiece* msg) {
  const upb_MiniTableField field = {4, 16, 67, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  return upb_Message_HasBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE void sentencepiece_SentencePieceText_SentencePiece_clear_end(sentencepiece_SentencePieceText_SentencePiece* msg) {
  const upb_MiniTableField field = {5, 20, 68, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  upb_Message_ClearBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE uint32_t sentencepiece_SentencePieceText_SentencePiece_end(const sentencepiece_SentencePieceText_SentencePiece* msg) {
  uint32_t default_val = (uint32_t)0u;
  uint32_t ret;
  const upb_MiniTableField field = {5, 20, 68, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  _upb_Message_GetNonExtensionField(UPB_UPCAST(msg), &field,
                                    &default_val, &ret);
  return ret;
}
UPB_INLINE bool sentencepiece_SentencePieceText_SentencePiece_has_end(const sentencepiece_SentencePieceText_SentencePiece* msg) {
  const upb_MiniTableField field = {5, 20, 68, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  return upb_Message_HasBaseField(UPB_UPCAST(msg), &field);
}

UPB_INLINE void sentencepiece_SentencePieceText_SentencePiece_set_piece(sentencepiece_SentencePieceText_SentencePiece* msg, upb_StringView value) {
  const upb_MiniTableField field = {1, 24, 64, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  upb_Message_SetBaseField((upb_Message*)msg, &field, &value);
}
UPB_INLINE void sentencepiece_SentencePieceText_SentencePiece_set_id(sentencepiece_SentencePieceText_SentencePiece* msg, uint32_t value) {
  const upb_MiniTableField field = {2, 12, 65, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  upb_Message_SetBaseField((upb_Message*)msg, &field, &value);
}
UPB_INLINE void sentencepiece_SentencePieceText_SentencePiece_set_surface(sentencepiece_SentencePieceText_SentencePiece* msg, upb_StringView value) {
  const upb_MiniTableField field = {3, UPB_SIZE(32, 40), 66, kUpb_NoSub, 12, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsAlternate | ((int)kUpb_FieldRep_StringView << kUpb_FieldRep_Shift)};
  upb_Message_SetBaseField((upb_Message*)msg, &field, &value);
}
UPB_INLINE void sentencepiece_SentencePieceText_SentencePiece_set_begin(sentencepiece_SentencePieceText_SentencePiece* msg, uint32_t value) {
  const upb_MiniTableField field = {4, 16, 67, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  upb_Message_SetBaseField((upb_Message*)msg, &field, &value);
}
UPB_INLINE void sentencepiece_SentencePieceText_SentencePiece_set_end(sentencepiece_SentencePieceText_SentencePiece* msg, uint32_t value) {
  const upb_MiniTableField field = {5, 20, 68, kUpb_NoSub, 13, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
  upb_Message_SetBaseField((upb_Message*)msg, &field, &value);
}

/* sentencepiece.NBestSentencePieceText */
UPB_INLINE sentencepiece_NBestSentencePieceText* sentencepiece_NBestSentencePieceText_new(upb_Arena* arena) {
  return (sentencepiece_NBestSentencePieceText*)_upb_Message_New(&sentencepiece__NBestSentencePieceText_msg_init, arena);
}
UPB_INLINE sentencepiece_NBestSentencePieceText* sentencepiece_NBestSentencePieceText_parse(const char* buf, size_t size,
                                        upb_Arena* arena) {
  sentencepiece_NBestSentencePieceText* ret = sentencepiece_NBestSentencePieceText_new(arena);
  if (!ret) return NULL;
  if (upb_Decode(buf, size, UPB_UPCAST(ret), &sentencepiece__NBestSentencePieceText_msg_init, NULL, 0,
                 arena) != kUpb_DecodeStatus_Ok) {
    return NULL;
  }
  return ret;
}
UPB_INLINE sentencepiece_NBestSentencePieceText* sentencepiece_NBestSentencePieceText_parse_ex(
    const char* buf, size_t size, const upb_ExtensionRegistry* extreg,
    int options, upb_Arena* arena) {
  sentencepiece_NBestSentencePieceText* ret = sentencepiece_NBestSentencePieceText_new(arena);
  if (!ret) return NULL;
  if (upb_Decode(buf, size, UPB_UPCAST(ret), &sentencepiece__NBestSentencePieceText_msg_init, extreg,
                 options, arena) != kUpb_DecodeStatus_Ok) {
    return NULL;
  }
  return ret;
}
UPB_INLINE char* sentencepiece_NBestSentencePieceText_serialize(const sentencepiece_NBestSentencePieceText* msg,
                                      upb_Arena* arena, size_t* len) {
  char* ptr;
  (void)upb_Encode(UPB_UPCAST(msg), &sentencepiece__NBestSentencePieceText_msg_init, 0, arena, &ptr, len);
  return ptr;
}
UPB_INLINE char* sentencepiece_NBestSentencePieceText_serialize_ex(const sentencepiece_NBestSentencePieceText* msg,
                                         int options, upb_Arena* arena,
                                         size_t* len) {
  char* ptr;
  (void)upb_Encode(UPB_UPCAST(msg), &sentencepiece__NBestSentencePieceText_msg_init, options, arena, &ptr, len);
  return ptr;
}
UPB_INLINE void sentencepiece_NBestSentencePieceText_clear_nbests(sentencepiece_NBestSentencePieceText* msg) {
  const upb_MiniTableField field = {1, 8, 0, UPB_SIZE(3, 4), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)};
  upb_Message_ClearBaseField(UPB_UPCAST(msg), &field);
}
UPB_INLINE const sentencepiece_SentencePieceText* const* sentencepiece_NBestSentencePieceText_nbests(const sentencepiece_NBestSentencePieceText* msg,
                                                  size_t* size) {
  const upb_MiniTableField field = {1, 8, 0, UPB_SIZE(3, 4), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)};
  UPB_PRIVATE(_upb_MiniTable_StrongReference)(&sentencepiece__SentencePieceText_msg_init);
  const upb_Array* arr = upb_Message_GetArray(UPB_UPCAST(msg), &field);
  if (arr) {
    if (size) *size = arr->UPB_PRIVATE(size);
    return (const sentencepiece_SentencePieceText* const*)upb_Array_DataPtr(arr);
  } else {
    if (size) *size = 0;
    return NULL;
  }
}

//
UPB_INLINE const upb_Array* _sentencepiece_NBestSentencePieceText_nbests_upb_array(
    const sentencepiece_NBestSentencePieceText* msg, size_t* size) {
  const upb_MiniTableField field = {1, 8, 0, UPB_SIZE(3, 4), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)};
  UPB_PRIVATE(_upb_MiniTable_StrongReference)(&sentencepiece__SentencePieceText_msg_init);
  const upb_Array* arr = upb_Message_GetArray(UPB_UPCAST(msg), &field);
  if (size) {
    *size = arr ? arr->UPB_PRIVATE(size) : 0;
  }
  return arr;
}

UPB_INLINE upb_Array* _sentencepiece_NBestSentencePieceText_nbests_mutable_upb_array(
    sentencepiece_NBestSentencePieceText* msg, size_t* size, upb_Arena* arena) {
  const upb_MiniTableField field = {1, 8, 0, UPB_SIZE(3, 4), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)};
  UPB_PRIVATE(_upb_MiniTable_StrongReference)(&sentencepiece__SentencePieceText_msg_init);
  upb_Array* arr = upb_Message_GetOrCreateMutableArray(UPB_UPCAST(msg),
                                                       &field, arena);
  if (size) {
    *size = arr ? arr->UPB_PRIVATE(size) : 0;
  }
  return arr;
}

UPB_INLINE sentencepiece_SentencePieceText** sentencepiece_NBestSentencePieceText_mutable_nbests(sentencepiece_NBestSentencePieceText* msg,
                                              size_t* size) {
  upb_MiniTableField field = {1, 8, 0, UPB_SIZE(3, 4), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)};
  UPB_PRIVATE(_upb_MiniTable_StrongReference)(&sentencepiece__SentencePieceText_msg_init);
  upb_Array* arr = upb_Message_GetMutableArray(UPB_UPCAST(msg), &field);
  if (arr) {
    if (size) *size = arr->UPB_PRIVATE(size);
    return (sentencepiece_SentencePieceText**)upb_Array_MutableDataPtr(arr);
  } else {
    if (size) *size = 0;
    return NULL;
  }
}

UPB_INLINE sentencepiece_SentencePieceText** sentencepiece_NBestSentencePieceText_resize_nbests(sentencepiece_NBestSentencePieceText* msg,
                                             size_t size,
                                             upb_Arena* arena) {
  upb_MiniTableField field = {1, 8, 0, UPB_SIZE(3, 4), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)};
  UPB_PRIVATE(_upb_MiniTable_StrongReference)(&sentencepiece__SentencePieceText_msg_init);
  return (sentencepiece_SentencePieceText**)upb_Message_ResizeArrayUninitialized(
      UPB_UPCAST(msg), &field, size, arena);
}
UPB_INLINE struct sentencepiece_SentencePieceText* sentencepiece_NBestSentencePieceText_add_nbests(
    sentencepiece_NBestSentencePieceText* msg, upb_Arena* arena) {
  upb_MiniTableField field = {1, 8, 0, UPB_SIZE(3, 4), 11, (int)kUpb_FieldMode_Array | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)};
  UPB_PRIVATE(_upb_MiniTable_StrongReference)(&sentencepiece__SentencePieceText_msg_init);
  upb_Array* arr = upb_Message_GetOrCreateMutableArray(
      UPB_UPCAST(msg), &field, arena);
  if (!arr || !UPB_PRIVATE(_upb_Array_ResizeUninitialized)(
                  arr, arr->UPB_PRIVATE(size) + 1, arena)) {
    return NULL;
  }
  struct sentencepiece_SentencePieceText* sub =
      (struct sentencepiece_SentencePieceText*)_upb_Message_New(&sentencepiece__SentencePieceText_msg_init, arena);
  if (!arr || !sub) return NULL;
  UPB_PRIVATE(_upb_Array_Set)
  (arr, arr->UPB_PRIVATE(size) - 1, &sub, sizeof(sub));
  return sub;
}

#ifdef __cplusplus
              } /* extern "C" */
#endif

#endif /* SENTENCEPIECE_PROTO_UPB_H__UPB_H_ */
