#!/usr/bin/env python3
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Amalgamation tool for SentencePiece Lite (C++20)."""

import argparse
import os
import re
import sys

HEADER_COPYRIGHT = """/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Auto-generated by SentencePiece Lite Amalgamation Tool (C++20).
// DO NOT EDIT DIRECTLY.
"""

FLATBUFFERS_HEADERS = [
    "base.h",
    "stl_emulation.h",
    "allocator.h",
    "default_allocator.h",
    "detached_buffer.h",
    "buffer.h",
    "vector_downward.h",
    "vector.h",
    "array.h",
    "string.h",
    "struct.h",
    "verifier.h",
    "buffer_ref.h",
    "table.h",
    "flatbuffer_builder.h",
    "flatbuffers.h",
]


def process_file(
    path: str,
    std_includes: set[str] | None = None,
    strip_internal: bool = True,
) -> str:
  """Cleans includes and guards from C++, collecting std headers if requested."""
  lines = []
  in_copyright_header = True
  with open(path, "r", encoding="utf-8", errors="ignore") as f:
    for line in f.read().splitlines():
      s = line.strip()
      if in_copyright_header:
        if s == "//" or (
            s.startswith("//")
            and any(
                k in s
                for k in (
                    "Copyright",
                    "Licensed under",
                    "you may not use",
                    "You may obtain",
                    "http://www.apache.org",
                    "Unless required",
                    "distributed under",
                    "WITHOUT WARRANTIES",
                    "See the License",
                    "limitations under",
                )
            )
        ):
          continue
        if s != "":
          in_copyright_header = False
      if s == "#pragma once" or re.match(
          r"^#(?:ifndef|define|endif\s+//)\s+(?:THIRD_PARTY_)?SENTENCEPIECE_LITE_.*",
          s,
      ):
        continue
      if strip_internal and re.match(
          r'^#include\s+["<](?:third_party/)?(?:sentencepiece|cached_sentencepiece|flatbuffers|absl|rapidhash|utf8|util/utf8|darts).*',
          s,
      ):
        continue
      m = re.match(r"^#include\s+<([a-zA-Z0-9_]+)>", s)
      if m and std_includes is not None:
        std_includes.add(m.group(1))
        continue
      lines.append(line)
  return "\n".join(lines)


def read(path: str) -> str:
  """Reads file content as utf-8 string."""
  with open(path, "r", encoding="utf-8", errors="ignore") as f:
    return f.read()


def find_path(candidates: list[str]) -> str:
  """Returns the first existing path from candidate list."""
  for c in candidates:
    if os.path.exists(c):
      return c
  return ""


def main():
  parser = argparse.ArgumentParser()
  parser.add_argument(
      "--repo_root",
      default=os.path.abspath(os.path.join(os.path.dirname(__file__), "..")),
  )
  parser.add_argument("--build_dir", default="")
  parser.add_argument("--output_dir", default="")
  args = parser.parse_args()

  repo_root = args.repo_root
  lite_dir = os.path.join(repo_root, "lite")
  build_dir = args.build_dir or os.path.join(lite_dir, "build")
  out_dir = args.output_dir or os.path.join(repo_root, "dist")
  os.makedirs(out_dir, exist_ok=True)

  fb_dir = find_path([
      os.path.join(build_dir, "_deps/flatbuffers-src/include/flatbuffers"),
      os.path.join(
          repo_root, "lite/build/_deps/flatbuffers-src/include/flatbuffers"
      ),
      os.path.join(
          repo_root, "build/_deps/flatbuffers-src/include/flatbuffers"
      ),
      "/usr/include/flatbuffers",
  ])
  fbs_gen = find_path([
      os.path.join(build_dir, "sentencepiece_lite_generated.h"),
      os.path.join(lite_dir, "build/sentencepiece_lite_generated.h"),
      os.path.join(repo_root, "build/lite/sentencepiece_lite_generated.h"),
  ])

  if not fb_dir or not fbs_gen:
    sys.exit(
        "Error: FlatBuffers headers or schema not found. Build with CMake"
        " first."
    )

  # 1. Header (sentencepiece_lite.h) - Dynamically collect std includes
  h_std = set()
  spm_h = process_file(
      os.path.join(lite_dir, "sentencepiece_lite.h"), std_includes=h_std
  )
  cached_h = process_file(
      os.path.join(lite_dir, "cached_sentencepiece_lite.h"), std_includes=h_std
  )

  h_out = [
      HEADER_COPYRIGHT,
      (
          "#ifndef SENTENCEPIECE_LITE_AMALGAMATED_H_\n#define"
          " SENTENCEPIECE_LITE_AMALGAMATED_H_\n"
      ),
  ]
  h_out.extend(f"#include <{h}>" for h in sorted(h_std))
  h_out.extend([
      "\n// === Public Interface ===",
      spm_h,
      "\n// === Cached Tokenizer Interface ===",
      cached_h,
      "\n#endif  // SENTENCEPIECE_LITE_AMALGAMATED_H_\n",
  ])

  out_h = os.path.join(out_dir, "sentencepiece_lite.h")
  with open(out_h, "w", encoding="utf-8") as f:
    f.write("\n".join(h_out))

  # 2. Source (sentencepiece_lite.cc) - Dynamically collect std includes
  cc_std = set()
  spm_cc = process_file(
      os.path.join(lite_dir, "sentencepiece_lite.cc"), std_includes=cc_std
  )
  cached_cc = process_file(
      os.path.join(lite_dir, "cached_sentencepiece_lite.cc"),
      std_includes=cc_std,
  )
  fbs_text = process_file(fbs_gen, strip_internal=True)

  cc_out = [HEADER_COPYRIGHT, '#include "sentencepiece_lite.h"\n']
  cc_out.extend(f"#include <{h}>" for h in sorted(cc_std))

  rapidhash = os.path.join(repo_root, "third_party/rapidhash/rapidhash.h")
  if os.path.exists(rapidhash):
    cc_out.extend(["\n// === Rapidhash ===", read(rapidhash)])

  cc_out.append("\n// === FlatBuffers C++ Runtime ===")
  for h in FLATBUFFERS_HEADERS:
    p = os.path.join(fb_dir, h)
    if os.path.exists(p):
      cc_out.extend([f"// --- flatbuffers/{h} ---", process_file(p)])

  cc_out.extend(["\n// === FlatBuffers Schema ===", fbs_text])
  cc_out.extend(["\n// === Core Implementation ===", spm_cc])
  cc_out.extend(["\n// === Cached Tokenizer Implementation ===", cached_cc])

  out_cc = os.path.join(out_dir, "sentencepiece_lite.cc")
  with open(out_cc, "w", encoding="utf-8") as f:
    f.write("\n".join(cc_out))

  print(
      f"Generated standalone amalgamation in {out_dir}/ (sentencepiece_lite.h,"
      " sentencepiece_lite.cc)"
  )


if __name__ == "__main__":
  main()
