name: CI for general build

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  release:
    types: [ created ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
          - os: ubuntu-24.04-arm
            arch: arm64
          - os: macos-latest
            arch: arm64
          - os: windows-latest
            arch: Win32
          - os: windows-latest
            arch: x64
          - os: windows-11-arm
            arch: ARM64

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write # svenstaro/upload-release-action

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Config for Windows
      if: runner.os == 'Windows'
      env:
        ARCH: ${{ matrix.arch }}
      run: cmake -A "$ARCH" -B build -DSPM_BUILD_TEST=ON -DSPM_ENABLE_SHARED=OFF -DCMAKE_INSTALL_PREFIX=build/root
    - name: Config for Linux/MacOSX
      if: runner.os != 'Windows'
      run: cmake -B build -DSPM_BUILD_TEST=ON -DCMAKE_INSTALL_PREFIX=build/root
      env:
        CMAKE_OSX_ARCHITECTURES: arm64

    - name: Build
      run: cmake --build build --config Release --target install --parallel 32

    - name: Test
      working-directory: build
      run: ctest -C Release --output-on-failure

    - name: Package
      working-directory: build
      run: cpack

    - name: Upload artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: artifacts-${{ matrix.os }}-${{ matrix.arch }}
        path: ./build/*.7z
        overwrite: false

    - name: Upload Release Assets
      if: startsWith(github.ref, 'refs/tags/')
      uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./build/*.7z
        tag: ${{ github.ref }}
        overwrite: true
        prerelease: true
        file_glob: true
        body: "This is my release text"
